### ISSUE TITLE
I suppose for the devs that vote republican there is nothing similar (yet)?

### ISSUE THREAD

**Issue by tistudios** [mattstauffer/tech-forward-gomix#11]
Enjoy Glitch, and the feeling of dev solidarity. I suppose politics will intertwine nonetheless...was turned off by it just being wholly anti-trump...although I understand the purpose of the website is to aggregate progressive content. Perhaps there should be something to balance it out? I guess I'll play.

**Comment by mattstauffer** [comment]
It’s an open source project. You can remix it and put entirely your own content into it if you’d like.

**Comment by tistudios** [comment]
Sometimes I miss obvious things. This is one of those times. Thanks Matt.

**Comment by mattstauffer** [comment]
:) no prob.
